CREATE TABLE IF NOT EXISTS cuentas (
    numero_cuenta VARCHAR(255) PRIMARY KEY,
    tipo_cuenta VARCHAR(255) NOT NULL,
    saldo_inicial DECIMAL(10, 2) NOT NULL,
    estado BOOLEAN NOT NULL,
    cliente_id VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    tipo_movimiento VARCHAR(255) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    saldo DECIMAL(10, 2) NOT NULL,
    numero_cuenta VARCHAR(255) NOT NULL,
    CONSTRAINT fk_movimiento_cuenta FOREIGN KEY (numero_cuenta) REFERENCES cuentas(numero_cuenta)
);
